### ISSUE TITLE
Loss bug in lmpt training

### ISSUE THREAD

**Issue by EricFu1120** [richard-peng-xia/LMPT#2]
Hi everyone, could you please help to figure out this error? Thanks!

Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main(args)
  File "train.py", line 223, in main
    loss_2 = hinge_loss(x, y)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/host/home/yong/Documents/LMPT/lmpt/csel.py", line 25, in forward
    class_weights = (1 / self.class_counts) ** self.gamma / torch.sum((1 / self.class_counts) ** self.gamma, dim=2)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

**Comment by richard-peng-xia** [comment]
Hi, I didn't encountered this problem during the running of the code, but I have briefly analyzed your problem.

It seems like you are attempting to perform an operation that involves the dimension "2" of a tensor, but the tensor only has dimensions in the range of [-2, 1]. This means that the tensor does not have a third dimension, which is causing the `IndexError` to be raised.

You need to check the shape of the tensor being used in that line of code `class_weights = (1 / self.class_counts) ** self.gamma / torch.sum((1 / self.class_counts) ** self.gamma, dim=2)` and ensure that you are accessing the correct dimensions.  Just make sure that the tensor has at least three dimensions.

Thanks for your interest in this work. If there are any more questions, please continue the discussion.

**Comment by EricFu1120** [comment]
Fixed! I made some mistakes when preparing the data. Thank you Richard!

**Comment by richard-peng-xia** [comment]
You're welcome! If it is convenient, I hope you could give this repo a star~ Thanks!

**Comment by hooxizz** [comment]
> @EricFu1120 Hi Eric, how can you fix the problem, I meet the same problem. Thanks in advance!

**Comment by Lansieuva** [comment]
Hi, how did you fix this problem. I think maybe there are some problems with the code.

**Comment by EricFu1120** [comment]
I just re-prepared my data, image-text pairs, as the format of COCO-LT and VOC-LT.

**Comment by skylie-xtj** [comment]
I encounter the same problem:
![image](https://github.com/richard-peng-xia/LMPT/assets/27881513/fb0edf61-b9eb-40fe-a163-1fb8431e07db)
The dimensions of x and y are (64,80,75). I wonder about the dimension of your data. Thanks a lot!

**Comment by JarvisUSTC** [comment]
I also met the error. I follow DBL to prepare the class freq, why the class-weight is three-dimension?

**Comment by richard-peng-xia** [comment]
Hi, all.

Thanks for interest in LMPT!

I have provided the dimensions of some key variables that I recorded during my training, which I hope will be useful to you. In addition, if everyone's error is similar, then I think you could check the format of the data, as @EricFu1120 said.

> [a](https://github.com/richard-peng-xia/LMPT/blob/main/lmpt/train.py#L214) # [batch_size, num_classes, context_length, context_dimension]
> [b](https://github.com/richard-peng-xia/LMPT/blob/main/lmpt/train.py#L215) # [batch_size, num_classes, context_length, context_dimension]
> [x](https://github.com/richard-peng-xia/LMPT/blob/main/lmpt/train.py#L216) # [batch_size, num_classes, context_length]
> [y](https://github.com/richard-peng-xia/LMPT/blob/main/lmpt/train.py#L217) # [batch_size, num_classes, context_length]

I hope that is clear now. Please feel free to ask incase there is any further query.

Thank you very much!
