### ISSUE TITLE
Question about the calculation of prediction probability

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [richard-peng-xia/LMPT#3]
Hi,

Thanks for your excellent work for long-tailed multi-label visual recognition. 

I am little confused about the calculation of prediction probability as shown below (formula 2). For example, let us assume that there exist three labels (i=a,b or c) in an image. We hope the prediction probability of the three labels are high enough. However, the prediction probability is normalized by the sum of all label classes like softmax, which can decline the prediction probability significantly when several labels exist. It seems really strange. Could you please give me some instructions?

![image](https://github.com/richard-peng-xia/LMPT/assets/75102173/2d557986-6322-4677-b47b-6189e0ac0071)

Best regards

**Comment by xiapeng1110** [comment]
Hi, Thank you for your great question. 

Several clip-based prompt tuning methods, like coop, cocoop, dualcoop, etc.,  all employed the softmax-like function. To ensure a fair comparison, we also utilized softmax for prediction probability. However, in multi-label tasks, it's possible that using the sigmoid activation function might yield better results. You could explore experimenting with that approach.

**Comment by GOZGOXGOYGO** [comment]
Thanks for your prompt reply! Actually, to deal with multi-label problem, DualCoOp outputs the predicted probability by calculating softmax value for a positive and negative pair, instead of calculating for all classes. In this way, the output can be regarded as probability for further ASL calculation. However, in your framework, the output probability will differ significantly with different number of classes for the reason of ustilizing softmax function for all classes. So I'm not sure whether it will decrease the performance of your framework. Anyhow, the presented results are quite excellent! :)

**Comment by xiapeng1110** [comment]
Yes. Your thinking is comprehensive, and indeed, the situation you mentioned could arise. Thank you for your question!
